nohup: ignoring input
INFO:aiogram:Bot: Lobbyist.uz [@Lobbyistuz_bot]
WARNING:aiogram:Updates were skipped successfully.
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:root:Данные сохранены для одобрения. Ключ: 5657091547_1754592250
INFO:root:Сохраненные данные: {'type': 'Чиқим', 'object_name': 'Эшонгузар', 'expense_type': 'хозтавар', 'currency_type': 'Сом', 'amount': '1000000000', 'payment_type': 'Нахт', 'comment': '-', 'dt': '2025-08-07 23:44:08', 'dt_for_sheet': '8/7/2025', 'vaqt': '23:44', 'user_id': 5657091547, 'pending_approval': True, 'approval_timestamp': 1754592250}
INFO:root:Все pending approvals: ['5657091547_1754592250']
INFO:root:Одобрение больших сумм вызвано: approve_large_5657091547_1754592250
INFO:root:Approval key: 5657091547_1754592250
INFO:root:Pending approvals: ['5657091547_1754592250']
INFO:root:Найдены данные для одобрения: {'type': 'Чиқим', 'object_name': 'Эшонгузар', 'expense_type': 'хозтавар', 'currency_type': 'Сом', 'amount': '1000000000', 'payment_type': 'Нахт', 'comment': '-', 'dt': '2025-08-07 23:44:08', 'dt_for_sheet': '8/7/2025', 'vaqt': '23:44', 'user_id': 5657091547, 'pending_approval': True, 'approval_timestamp': 1754592250}
ERROR:root:Ошибка при одобрении: [Errno 2] No such file or directory: 'credentials.json'
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/mohirbek/Projects/SFX_SAVDO/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-08-09 22:52:43,800 - __main__ - INFO - 🔄 Запуск бота...
2025-08-09 22:52:44,117 - aiogram - INFO - Bot: Lobbyist.uz [@Lobbyistuz_bot]
2025-08-09 22:52:44,329 - aiogram - WARNING - Updates were skipped successfully.
2025-08-09 22:52:44,329 - __main__ - INFO - 🚀 Бот запускается...
2025-08-09 22:52:44,602 - __main__ - INFO - ✅ Команды бота установлены
2025-08-09 22:52:44,611 - __main__ - INFO - 📤 Отправка уведомлений 3 пользователям...
2025-08-09 22:52:45,544 - __main__ - INFO - ✅ Уведомления отправлены: 3/3 успешно, 0 неудачно
2025-08-09 22:52:45,544 - __main__ - INFO - ✅ Уведомления отправлены
2025-08-09 22:52:45,544 - __main__ - INFO - ✅ Бот успешно запущен и готов к работе
2025-08-09 22:52:45,544 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-08-09 22:53:51,713 - root - INFO - Дублирование предотвращено для пользователя 5048593195
2025-08-09 22:53:51,845 - root - ERROR - ✅ Уведомление отправлено админу 5048593195 (Mahmud aka)
2025-08-09 22:53:54,614 - root - ERROR - ✅ Уведомление отправлено админу 5657091547 (Admin)
2025-08-09 22:53:54,747 - root - ERROR - ✅ Уведомление отправлено админу 5048593195 (Mahmud aka)
2025-08-09 22:53:54,885 - root - ERROR - ✅ Уведомление отправлено админу 5657091547 (Admin)
2025-08-09 22:56:06,963 - root - INFO - Дублирование предотвращено для пользователя 5657091547
2025-08-09 22:56:27,313 - root - ERROR - ✅ Уведомление отправлено админу 5048593195 (Mahmud aka)
2025-08-09 22:56:27,639 - root - ERROR - ✅ Уведомление отправлено админу 5657091547 (Admin)
2025-08-09 22:56:28,098 - root - ERROR - ✅ Уведомление отправлено админу 5048593195 (Mahmud aka)
2025-08-09 22:56:28,359 - root - ERROR - ✅ Уведомление отправлено админу 5657091547 (Admin)
2025-08-09 22:58:51,812 - root - INFO - Сохраняем данные в БД. Ключ: 5657091547_1754762331, JSON: {"type": "\u0427\u0438\u049b\u0438\u043c", "object_name": "\u041c\u043e\u0442\u0440\u0438\u0434 \u04...
2025-08-09 22:58:51,859 - root - INFO - Данные успешно сохранены в БД для ключа: 5657091547_1754762331
2025-08-09 22:58:51,860 - root - INFO - Данные сохранены в базе данных для одобрения. Ключ: 5657091547_1754762331
2025-08-09 22:58:51,860 - root - INFO - Сохраненные данные: {'type': 'Чиқим', 'object_name': 'Мотрид катеж', 'expense_type': 'Премия', 'currency_type': 'Доллар', 'amount': '14000', 'exchange_rate': '12900', 'payment_type': 'Нахт', 'comment': '-', 'dt': '2025-08-09 22:58:50', 'dt_for_sheet': '8/9/2025', 'vaqt': '22:58', 'user_id': 5657091547, 'pending_approval': True, 'approval_timestamp': 1754762331}
2025-08-09 22:58:51,869 - root - INFO - Найдено админов в базе: 3
2025-08-09 22:58:51,869 - root - INFO - Пытаемся отправить уведомление админу 5048593195 (Mahmud aka)
2025-08-09 22:58:52,034 - root - INFO - ✅ Уведомление успешно отправлено админу 5048593195
2025-08-09 22:58:52,034 - root - INFO - Пытаемся отправить уведомление админу 7983512278 (Mohirbek 2)
2025-08-09 22:58:52,178 - root - INFO - ✅ Уведомление успешно отправлено админу 7983512278
2025-08-09 22:58:52,179 - root - INFO - Пытаемся отправить уведомление админу 5657091547 (Admin)
2025-08-09 22:58:52,339 - root - INFO - ✅ Уведомление успешно отправлено админу 5657091547
2025-08-09 22:59:03,555 - root - INFO - Одобрение больших сумм вызвано: approve_large_5657091547_1754762331
2025-08-09 22:59:03,564 - root - INFO - Approval key: 5657091547_1754762331
2025-08-09 22:59:03,572 - root - INFO - Получены данные из БД для ключа 5657091547_1754762331. Тип: <class 'dict'>
2025-08-09 22:59:03,572 - root - INFO - Данные уже в формате словаря: {'dt': '2025-08-09 22:58:50', 'type': 'Чиқим', 'vaqt': '22:58', 'amount': '14000', 'comment': '-', 'user_id': 5657091547, 'object_name': 'Мотрид катеж', 'dt_for_sheet': '8/9/2025', 'expense_type': 'Премия', 'payment_type': 'Нахт', 'currency_type': 'Доллар', 'exchange_rate': '12900', 'pending_approval': True, 'approval_timestamp': 1754762331}
2025-08-09 22:59:03,573 - root - INFO - Найдены данные для одобрения: {'dt': '2025-08-09 22:58:50', 'type': 'Чиқим', 'vaqt': '22:58', 'amount': '14000', 'comment': '-', 'user_id': 5657091547, 'object_name': 'Мотрид катеж', 'dt_for_sheet': '8/9/2025', 'expense_type': 'Премия', 'payment_type': 'Нахт', 'currency_type': 'Доллар', 'exchange_rate': '12900', 'pending_approval': True, 'approval_timestamp': 1754762331}
2025-08-09 22:59:11,814 - root - INFO - Данные отправлены в Google Sheet
2025-08-09 22:59:13,968 - root - INFO - Одобрение больших сумм вызвано: approve_large_5657091547_1754762331
2025-08-09 22:59:13,976 - root - INFO - Approval key: 5657091547_1754762331
2025-08-09 22:59:13,986 - root - INFO - Получены данные из БД для ключа 5657091547_1754762331. Тип: <class 'dict'>
2025-08-09 22:59:13,986 - root - INFO - Данные уже в формате словаря: {'dt': '2025-08-09 22:58:50', 'type': 'Чиқим', 'vaqt': '22:58', 'amount': '14000', 'comment': '-', 'user_id': 5657091547, 'object_name': 'Мотрид катеж', 'dt_for_sheet': '8/9/2025', 'expense_type': 'Премия', 'payment_type': 'Нахт', 'currency_type': 'Доллар', 'exchange_rate': '12900', 'pending_approval': True, 'approval_timestamp': 1754762331}
2025-08-09 22:59:13,986 - root - INFO - Найдены данные для одобрения: {'dt': '2025-08-09 22:58:50', 'type': 'Чиқим', 'vaqt': '22:58', 'amount': '14000', 'comment': '-', 'user_id': 5657091547, 'object_name': 'Мотрид катеж', 'dt_for_sheet': '8/9/2025', 'expense_type': 'Премия', 'payment_type': 'Нахт', 'currency_type': 'Доллар', 'exchange_rate': '12900', 'pending_approval': True, 'approval_timestamp': 1754762331}
2025-08-09 22:59:13,986 - root - INFO - Дублирование предотвращено для пользователя 5657091547
2025-08-09 22:59:13,986 - root - INFO - Дублирование предотвращено при одобрении
2025-08-09 22:59:14,126 - root - ERROR - Ошибка при остановке FSM для пользователя 5657091547: 'FSMContext' object has no attribute 'key'
2025-08-09 22:59:17,520 - root - ERROR - Ошибка при остановке FSM для пользователя 5657091547: 'FSMContext' object has no attribute 'key'
2025-08-09 22:59:17,653 - root - INFO - ✅ Уведомление об одобрении отправлено админу 5048593195 (Mahmud aka)
2025-08-09 22:59:20,401 - root - INFO - ✅ Уведомление об одобрении отправлено админу 5657091547 (Admin)
2025-08-09 22:59:20,569 - root - INFO - ✅ Уведомление об одобрении отправлено админу 7983512278 (Mohirbek 2)
2025-08-09 22:59:20,695 - root - WARNING - Callback query истек или недействителен: Query is too old and response timeout expired or query id is invalid
2025-08-09 22:59:20,732 - root - INFO - ✅ Уведомление об одобрении отправлено админу 5657091547 (Admin)
2025-08-09 22:59:21,059 - root - WARNING - Callback query истек или недействителен: Query is too old and response timeout expired or query id is invalid
2025-08-09 23:08:34,611 - root - INFO - Дублирование предотвращено для пользователя 5657091547
2025-08-09 23:08:39,295 - root - ERROR - ✅ Уведомление отправлено админу 5048593195 (Mahmud aka)
2025-08-09 23:08:41,329 - root - ERROR - ✅ Уведомление отправлено админу 7983512278 (Mohirbek 2)
2025-08-09 23:08:41,498 - root - ERROR - ✅ Уведомление отправлено админу 5048593195 (Mahmud aka)
2025-08-09 23:08:41,504 - root - ERROR - ✅ Уведомление отправлено админу 5657091547 (Admin)
2025-08-09 23:08:41,702 - root - ERROR - ✅ Уведомление отправлено админу 7983512278 (Mohirbek 2)
2025-08-09 23:08:41,942 - root - ERROR - ✅ Уведомление отправлено админу 5657091547 (Admin)
2025-08-09 23:30:49,914 - __main__ - INFO - 🛑 Бот останавливается...
2025-08-09 23:30:49,915 - __main__ - INFO - ✅ Хранилище закрыто
2025-08-09 23:30:49,915 - aiogram.dispatcher.dispatcher - INFO - Stop polling...
2025-08-09 23:30:49,915 - aiogram - WARNING - Goodbye!
2025-08-10 00:11:16,110 - __main__ - INFO - 🔄 Запуск бота...
2025-08-10 00:11:16,508 - aiogram - INFO - Bot: Lobbyist.uz [@Lobbyistuz_bot]
2025-08-10 00:11:16,710 - aiogram - WARNING - Updates were skipped successfully.
2025-08-10 00:11:16,710 - __main__ - INFO - 🚀 Бот запускается...
2025-08-10 00:11:16,817 - __main__ - INFO - ✅ Команды бота установлены
2025-08-10 00:11:16,827 - __main__ - INFO - 📤 Отправка уведомлений 3 пользователям...
2025-08-10 00:11:17,593 - __main__ - INFO - ✅ Уведомления отправлены: 3/3 успешно, 0 неудачно
2025-08-10 00:11:17,594 - __main__ - INFO - ✅ Уведомления отправлены
2025-08-10 00:11:17,594 - __main__ - INFO - ✅ Бот успешно запущен и готов к работе
2025-08-10 00:11:17,594 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-08-10 00:11:55,337 - root - INFO - skip_comment_btn вызван для пользователя 5657091547
2025-08-10 00:11:56,765 - root - INFO - process_confirm вызван для пользователя 5657091547 с данными: confirm_yes
2025-08-10 00:12:05,502 - root - INFO - process_confirm вызван для пользователя 5657091547 с данными: confirm_yes
2025-08-10 00:12:05,503 - root - INFO - Дублирование предотвращено для пользователя 5657091547
2025-08-10 00:12:07,623 - root - INFO - Отправляем баланс в сомах пользователю 5657091547: 101506000
2025-08-10 00:12:09,758 - root - INFO - Сообщение о балансе для пользователя 5657091547 пропущено как дубликат
2025-08-10 00:12:12,606 - root - INFO - Информация о балансе добавлена в уведомление для админов: 💰 <b>Balans:</b>
💰 Balans: somda 101506000
2025-08-10 00:12:12,629 - root - INFO - Отправляем уведомления 3 админам
2025-08-10 00:12:14,688 - root - INFO - Информация о балансе добавлена в уведомление для админов: 💰 <b>Balans:</b>
💰 Balans: somda 101506000
2025-08-10 00:12:14,698 - root - INFO - Отправляем уведомления 3 админам
2025-08-10 00:12:14,700 - root - INFO - ✅ Уведомление отправлено админу 5048593195 (Mahmud aka)
2025-08-10 00:12:14,866 - root - INFO - ✅ Уведомление отправлено админу 5048593195 (Mahmud aka)
2025-08-10 00:12:14,869 - root - INFO - ✅ Уведомление отправлено админу 7983512278 (Mohirbek 2)
2025-08-10 00:12:15,021 - root - INFO - ✅ Уведомление отправлено админу 7983512278 (Mohirbek 2)
2025-08-10 00:12:15,022 - root - INFO - ✅ Уведомление отправлено админу 5657091547 (Admin)
2025-08-10 00:12:15,155 - root - INFO - ✅ Уведомление отправлено админу 5657091547 (Admin)
2025-08-10 00:12:23,674 - __main__ - INFO - 🛑 Бот останавливается...
2025-08-10 00:12:23,675 - __main__ - INFO - ✅ Хранилище закрыто
2025-08-10 00:12:23,675 - aiogram.dispatcher.dispatcher - INFO - Stop polling...
2025-08-10 00:12:23,675 - aiogram - WARNING - Goodbye!
2025-08-10 00:21:48,306 - __main__ - INFO - 🔄 Запуск бота...
2025-08-10 00:21:48,694 - aiogram - INFO - Bot: Lobbyist.uz [@Lobbyistuz_bot]
2025-08-10 00:21:48,958 - aiogram - WARNING - Updates were skipped successfully.
2025-08-10 00:21:48,959 - __main__ - INFO - 🚀 Бот запускается...
2025-08-10 00:21:49,108 - __main__ - INFO - ✅ Команды бота установлены
2025-08-10 00:21:49,117 - __main__ - INFO - 📤 Отправка уведомлений 3 пользователям...
2025-08-10 00:21:50,213 - __main__ - INFO - ✅ Уведомления отправлены: 3/3 успешно, 0 неудачно
2025-08-10 00:21:50,213 - __main__ - INFO - ✅ Уведомления отправлены
2025-08-10 00:21:50,213 - __main__ - INFO - ✅ Бот успешно запущен и готов к работе
2025-08-10 00:21:50,213 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-08-10 00:22:07,768 - root - INFO - skip_comment_btn вызван для пользователя 5657091547
2025-08-10 00:22:09,294 - root - INFO - process_confirm вызван для пользователя 5657091547 с данными: confirm_yes
2025-08-10 00:22:09,311 - root - INFO - Сохраняем данные в БД. Ключ: 5657091547_1754767329, JSON: {"type": "\u0427\u0438\u049b\u0438\u043c", "object_name": "\u041c\u0430\u0445\u0434\u0443\u043c\u043...
2025-08-10 00:22:09,325 - root - INFO - Данные успешно сохранены в БД для ключа: 5657091547_1754767329
2025-08-10 00:22:09,326 - root - INFO - Данные сохранены в базе данных для одобрения. Ключ: 5657091547_1754767329
2025-08-10 00:22:09,326 - root - INFO - Сохраненные данные: {'type': 'Чиқим', 'object_name': 'Махдуми Азам', 'expense_type': 'хозтавар', 'currency_type': 'Сом', 'amount': '20000000000', 'payment_type': 'Пластик', 'comment': '-', 'dt': '2025-08-10 00:22:07', 'dt_for_sheet': '8/10/2025', 'vaqt': '00:22', 'user_id': 5657091547, 'pending_approval': True, 'approval_timestamp': 1754767329}
2025-08-10 00:22:09,334 - root - INFO - Найдено админов в базе: 3
2025-08-10 00:22:09,334 - root - INFO - Пытаемся отправить уведомление админу 5048593195 (Mahmud aka)
2025-08-10 00:22:09,474 - root - INFO - ✅ Уведомление успешно отправлено админу 5048593195
2025-08-10 00:22:09,474 - root - INFO - Пытаемся отправить уведомление админу 7983512278 (Mohirbek 2)
2025-08-10 00:22:09,596 - root - INFO - ✅ Уведомление успешно отправлено админу 7983512278
2025-08-10 00:22:09,596 - root - INFO - Пытаемся отправить уведомление админу 5657091547 (Admin)
2025-08-10 00:22:09,741 - root - INFO - ✅ Уведомление успешно отправлено админу 5657091547
2025-08-10 00:22:29,264 - root - INFO - Одобрение больших сумм вызвано: approve_large_5657091547_1754767329
2025-08-10 00:22:29,273 - root - INFO - Approval key: 5657091547_1754767329
2025-08-10 00:22:29,292 - root - INFO - Получены данные из БД для ключа 5657091547_1754767329. Тип: <class 'dict'>
2025-08-10 00:22:29,292 - root - INFO - Данные уже в формате словаря: {'dt': '2025-08-10 00:22:07', 'type': 'Чиқим', 'vaqt': '00:22', 'amount': '20000000000', 'comment': '-', 'user_id': 5657091547, 'object_name': 'Махдуми Азам', 'dt_for_sheet': '8/10/2025', 'expense_type': 'хозтавар', 'payment_type': 'Пластик', 'currency_type': 'Сом', 'pending_approval': True, 'approval_timestamp': 1754767329}
2025-08-10 00:22:29,292 - root - INFO - Найдены данные для одобрения: {'dt': '2025-08-10 00:22:07', 'type': 'Чиқим', 'vaqt': '00:22', 'amount': '20000000000', 'comment': '-', 'user_id': 5657091547, 'object_name': 'Махдуми Азам', 'dt_for_sheet': '8/10/2025', 'expense_type': 'хозтавар', 'payment_type': 'Пластик', 'currency_type': 'Сом', 'pending_approval': True, 'approval_timestamp': 1754767329}
2025-08-10 00:22:37,129 - root - INFO - Данные отправлены в Google Sheet
2025-08-10 00:22:40,401 - root - INFO - Отправляем баланс в сомах пользователю 5657091547: -19898494000
2025-08-10 00:22:40,681 - root - ERROR - Ошибка при остановке FSM для пользователя 5657091547: 'FSMContext' object has no attribute 'key'
2025-08-10 00:22:40,825 - root - INFO - Одобрение больших сумм вызвано: approve_large_5657091547_1754767329
2025-08-10 00:22:40,834 - root - INFO - Approval key: 5657091547_1754767329
2025-08-10 00:22:40,842 - root - WARNING - Ключ одобрения 5657091547_1754767329 уже был обработан или не существует
2025-08-10 00:22:40,843 - root - INFO - Callback 6618808030988036953 уже был обработан, пропускаем
2025-08-10 00:22:41,024 - root - INFO - ✅ Уведомление об одобрении отправлено админу 5048593195 (Mahmud aka)
2025-08-10 00:22:41,222 - root - INFO - ✅ Уведомление об одобрении отправлено админу 7983512278 (Mohirbek 2)
2025-08-10 00:22:41,352 - root - INFO - ✅ Уведомление об одобрении отправлено админу 5657091547 (Admin)
2025-08-10 00:23:30,353 - __main__ - INFO - 🛑 Бот останавливается...
2025-08-10 00:23:30,353 - __main__ - INFO - ✅ Хранилище закрыто
2025-08-10 00:23:30,354 - aiogram.dispatcher.dispatcher - INFO - Stop polling...
2025-08-10 00:23:30,354 - aiogram - WARNING - Goodbye!
2025-08-10 00:24:02,490 - __main__ - INFO - 🔄 Запуск бота...
2025-08-10 00:24:02,842 - aiogram - INFO - Bot: Lobbyist.uz [@Lobbyistuz_bot]
2025-08-10 00:24:03,044 - aiogram - WARNING - Updates were skipped successfully.
2025-08-10 00:24:03,045 - __main__ - INFO - 🚀 Бот запускается...
2025-08-10 00:24:03,162 - __main__ - INFO - ✅ Команды бота установлены
2025-08-10 00:24:03,172 - __main__ - INFO - 📤 Отправка уведомлений 3 пользователям...
2025-08-10 00:24:03,881 - __main__ - INFO - ✅ Уведомления отправлены: 3/3 успешно, 0 неудачно
2025-08-10 00:24:03,881 - __main__ - INFO - ✅ Уведомления отправлены
2025-08-10 00:24:03,881 - __main__ - INFO - ✅ Бот успешно запущен и готов к работе
2025-08-10 00:24:03,881 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-08-10 00:24:20,338 - root - INFO - skip_comment_btn вызван для пользователя 5657091547
2025-08-10 00:24:21,545 - root - INFO - process_confirm вызван для пользователя 5657091547 с данными: confirm_yes
2025-08-10 00:24:28,155 - root - INFO - process_confirm вызван для пользователя 5657091547 с данными: confirm_yes
2025-08-10 00:24:28,156 - root - INFO - Дублирование предотвращено для пользователя 5657091547
2025-08-10 00:24:30,873 - root - INFO - Отправляем баланс в сомах пользователю 5657091547: -19898481655
2025-08-10 00:24:34,818 - root - INFO - Сообщение о балансе для пользователя 5657091547 пропущено как дубликат
2025-08-10 00:24:37,138 - root - INFO - Информация о балансе добавлена в уведомление для админов: 💰 <b>Balans:</b>
💰 Balans: somda -19898481655
2025-08-10 00:24:37,158 - root - INFO - Отправляем уведомления 3 админам
2025-08-10 00:24:39,245 - root - INFO - Информация о балансе добавлена в уведомление для админов: 💰 <b>Balans:</b>
💰 Balans: somda -19898481655
2025-08-10 00:24:39,254 - root - INFO - Отправляем уведомления 3 админам
2025-08-10 00:24:39,256 - root - INFO - ✅ Уведомление отправлено админу 5048593195 (Mahmud aka)
2025-08-10 00:24:39,454 - root - INFO - ✅ Уведомление отправлено админу 5048593195 (Mahmud aka)
2025-08-10 00:24:39,455 - root - INFO - ✅ Уведомление отправлено админу 7983512278 (Mohirbek 2)
2025-08-10 00:24:39,662 - root - INFO - ✅ Уведомление отправлено админу 7983512278 (Mohirbek 2)
2025-08-10 00:24:39,663 - root - INFO - ✅ Уведомление отправлено админу 5657091547 (Admin)
2025-08-10 00:24:39,916 - root - INFO - ✅ Уведомление отправлено админу 5657091547 (Admin)
2025-08-10 00:25:12,270 - root - INFO - skip_comment_btn вызван для пользователя 5657091547
2025-08-10 00:25:13,850 - root - INFO - process_confirm вызван для пользователя 5657091547 с данными: confirm_yes
2025-08-10 00:25:13,866 - root - INFO - Сохраняем данные в БД. Ключ: 5657091547_1754767513, JSON: {"type": "\u0427\u0438\u049b\u0438\u043c", "object_name": "\u041a\u043e\u0436\u0430 \u0437\u0430\u04...
2025-08-10 00:25:13,880 - root - INFO - Данные успешно сохранены в БД для ключа: 5657091547_1754767513
2025-08-10 00:25:13,880 - root - INFO - Данные сохранены в базе данных для одобрения. Ключ: 5657091547_1754767513
2025-08-10 00:25:13,880 - root - INFO - Сохраненные данные: {'type': 'Чиқим', 'object_name': 'Кожа завод', 'expense_type': 'хозтавар', 'currency_type': 'Доллар', 'amount': '10000', 'exchange_rate': '12700', 'payment_type': 'Пластик', 'comment': '-', 'dt': '2025-08-10 00:25:12', 'dt_for_sheet': '8/10/2025', 'vaqt': '00:25', 'user_id': 5657091547, 'pending_approval': True, 'approval_timestamp': 1754767513}
2025-08-10 00:25:13,889 - root - INFO - Найдено админов в базе: 3
2025-08-10 00:25:13,889 - root - INFO - Пытаемся отправить уведомление админу 5048593195 (Mahmud aka)
2025-08-10 00:25:14,084 - root - INFO - ✅ Уведомление успешно отправлено админу 5048593195
2025-08-10 00:25:14,084 - root - INFO - Пытаемся отправить уведомление админу 7983512278 (Mohirbek 2)
2025-08-10 00:25:14,291 - root - INFO - ✅ Уведомление успешно отправлено админу 7983512278
2025-08-10 00:25:14,291 - root - INFO - Пытаемся отправить уведомление админу 5657091547 (Admin)
2025-08-10 00:25:14,524 - root - INFO - ✅ Уведомление успешно отправлено админу 5657091547
2025-08-10 00:25:18,558 - root - INFO - Одобрение больших сумм вызвано: approve_large_5657091547_1754767513
2025-08-10 00:25:18,568 - root - INFO - Approval key: 5657091547_1754767513
2025-08-10 00:25:18,585 - root - INFO - Получены данные из БД для ключа 5657091547_1754767513. Тип: <class 'dict'>
2025-08-10 00:25:18,586 - root - INFO - Данные уже в формате словаря: {'dt': '2025-08-10 00:25:12', 'type': 'Чиқим', 'vaqt': '00:25', 'amount': '10000', 'comment': '-', 'user_id': 5657091547, 'object_name': 'Кожа завод', 'dt_for_sheet': '8/10/2025', 'expense_type': 'хозтавар', 'payment_type': 'Пластик', 'currency_type': 'Доллар', 'exchange_rate': '12700', 'pending_approval': True, 'approval_timestamp': 1754767513}
2025-08-10 00:25:18,586 - root - INFO - Найдены данные для одобрения: {'dt': '2025-08-10 00:25:12', 'type': 'Чиқим', 'vaqt': '00:25', 'amount': '10000', 'comment': '-', 'user_id': 5657091547, 'object_name': 'Кожа завод', 'dt_for_sheet': '8/10/2025', 'expense_type': 'хозтавар', 'payment_type': 'Пластик', 'currency_type': 'Доллар', 'exchange_rate': '12700', 'pending_approval': True, 'approval_timestamp': 1754767513}
2025-08-10 00:25:25,640 - root - INFO - Данные отправлены в Google Sheet
2025-08-10 00:25:27,655 - root - INFO - Отправляем баланс в долларах пользователю 5657091547: 21303
2025-08-10 00:25:27,772 - root - INFO - Одобрение больших сумм вызвано: approve_large_5657091547_1754767513
2025-08-10 00:25:27,781 - root - INFO - Approval key: 5657091547_1754767513
2025-08-10 00:25:27,798 - root - INFO - Получены данные из БД для ключа 5657091547_1754767513. Тип: <class 'dict'>
2025-08-10 00:25:27,798 - root - INFO - Данные уже в формате словаря: {'dt': '2025-08-10 00:25:12', 'type': 'Чиқим', 'vaqt': '00:25', 'amount': '10000', 'comment': '-', 'user_id': 5657091547, 'object_name': 'Кожа завод', 'dt_for_sheet': '8/10/2025', 'expense_type': 'хозтавар', 'payment_type': 'Пластик', 'currency_type': 'Доллар', 'exchange_rate': '12700', 'pending_approval': True, 'approval_timestamp': 1754767513}
2025-08-10 00:25:27,798 - root - INFO - Найдены данные для одобрения: {'dt': '2025-08-10 00:25:12', 'type': 'Чиқим', 'vaqt': '00:25', 'amount': '10000', 'comment': '-', 'user_id': 5657091547, 'object_name': 'Кожа завод', 'dt_for_sheet': '8/10/2025', 'expense_type': 'хозтавар', 'payment_type': 'Пластик', 'currency_type': 'Доллар', 'exchange_rate': '12700', 'pending_approval': True, 'approval_timestamp': 1754767513}
2025-08-10 00:25:27,798 - root - INFO - Дублирование предотвращено для пользователя 5657091547
2025-08-10 00:25:27,799 - root - INFO - Дублирование предотвращено при одобрении
2025-08-10 00:25:27,927 - root - ERROR - Ошибка при остановке FSM для пользователя 5657091547: 'FSMContext' object has no attribute 'key'
2025-08-10 00:25:27,967 - root - ERROR - Ошибка при остановке FSM для пользователя 5657091547: 'FSMContext' object has no attribute 'key'
2025-08-10 00:25:28,227 - root - INFO - ✅ Уведомление об одобрении отправлено админу 5048593195 (Mahmud aka)
2025-08-10 00:25:28,268 - root - INFO - ✅ Уведомление об одобрении отправлено админу 5048593195 (Mahmud aka)
2025-08-10 00:25:28,368 - root - INFO - ✅ Уведомление об одобрении отправлено админу 7983512278 (Mohirbek 2)
2025-08-10 00:25:28,388 - root - INFO - ✅ Уведомление об одобрении отправлено админу 7983512278 (Mohirbek 2)
2025-08-10 00:25:28,486 - root - INFO - ✅ Уведомление об одобрении отправлено админу 5657091547 (Admin)
2025-08-10 00:25:28,505 - root - INFO - ✅ Уведомление об одобрении отправлено админу 5657091547 (Admin)
2025-08-10 00:26:21,086 - root - INFO - skip_comment_btn вызван для пользователя 5657091547
2025-08-10 00:26:22,751 - root - INFO - process_confirm вызван для пользователя 5657091547 с данными: confirm_yes
2025-08-10 00:26:33,368 - root - INFO - Отправляем баланс в сомах пользователю 5657091547: -19898494000
2025-08-10 00:26:35,707 - root - INFO - Информация о балансе добавлена в уведомление для админов: 💰 <b>Balans:</b>
💰 Balans: somda -19898494000
2025-08-10 00:26:35,718 - root - INFO - Отправляем уведомления 3 админам
2025-08-10 00:26:35,855 - root - INFO - ✅ Уведомление отправлено админу 5048593195 (Mahmud aka)
2025-08-10 00:26:35,984 - root - INFO - ✅ Уведомление отправлено админу 7983512278 (Mohirbek 2)
2025-08-10 00:26:36,151 - root - INFO - ✅ Уведомление отправлено админу 5657091547 (Admin)
2025-08-10 00:28:33,263 - __main__ - INFO - 🛑 Бот останавливается...
2025-08-10 00:28:33,263 - __main__ - INFO - ✅ Хранилище закрыто
2025-08-10 00:28:33,263 - aiogram.dispatcher.dispatcher - INFO - Stop polling...
2025-08-10 00:28:33,264 - aiogram - WARNING - Goodbye!
2025-08-10 00:31:41,909 - __main__ - INFO - 🔄 Запуск бота...
2025-08-10 00:31:42,306 - aiogram - INFO - Bot: Lobbyist.uz [@Lobbyistuz_bot]
2025-08-10 00:31:42,528 - aiogram - WARNING - Updates were skipped successfully.
2025-08-10 00:31:42,528 - __main__ - INFO - 🚀 Бот запускается...
2025-08-10 00:31:42,640 - __main__ - INFO - ✅ Команды бота установлены
2025-08-10 00:31:42,649 - __main__ - INFO - 📤 Отправка уведомлений 3 пользователям...
2025-08-10 00:31:43,426 - __main__ - INFO - ✅ Уведомления отправлены: 3/3 успешно, 0 неудачно
2025-08-10 00:31:43,426 - __main__ - INFO - ✅ Уведомления отправлены
2025-08-10 00:31:43,427 - __main__ - INFO - ✅ Бот успешно запущен и готов к работе
2025-08-10 00:31:43,427 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-08-10 00:31:46,608 - __main__ - INFO - 🛑 Бот останавливается...
2025-08-10 00:31:46,608 - __main__ - INFO - ✅ Хранилище закрыто
2025-08-10 00:31:46,609 - aiogram.dispatcher.dispatcher - INFO - Stop polling...
2025-08-10 00:31:46,609 - aiogram - WARNING - Goodbye!
2025-08-10 00:33:58,816 - __main__ - INFO - 🔄 Запуск бота...
2025-08-10 00:33:59,172 - aiogram - INFO - Bot: Lobbyist.uz [@Lobbyistuz_bot]
2025-08-10 00:33:59,367 - aiogram - WARNING - Updates were skipped successfully.
2025-08-10 00:33:59,367 - __main__ - INFO - 🚀 Бот запускается...
2025-08-10 00:33:59,537 - __main__ - INFO - ✅ Команды бота установлены
2025-08-10 00:33:59,547 - __main__ - INFO - 📤 Отправка уведомлений 3 пользователям...
2025-08-10 00:34:00,561 - __main__ - INFO - ✅ Уведомления отправлены: 3/3 успешно, 0 неудачно
2025-08-10 00:34:00,561 - __main__ - INFO - ✅ Уведомления отправлены
2025-08-10 00:34:00,561 - __main__ - INFO - ✅ Бот успешно запущен и готов к работе
2025-08-10 00:34:00,561 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-08-10 00:34:02,726 - root - INFO - Команда /reboot вызвана пользователем 5657091547
2025-08-10 00:34:03,177 - root - INFO - Главное меню показано пользователю 5657091547
2025-08-10 00:34:03,177 - root - INFO - Пользователь 5657091547 возвращен к начальному состоянию FSM
2025-08-10 00:34:09,043 - root - INFO - Команда /reboot вызвана пользователем 5657091547
2025-08-10 00:34:09,375 - root - INFO - Главное меню показано пользователю 5657091547
2025-08-10 00:34:09,375 - root - INFO - Пользователь 5657091547 возвращен к начальному состоянию FSM
2025-08-10 00:34:19,663 - __main__ - INFO - 🛑 Бот останавливается...
2025-08-10 00:34:19,663 - __main__ - INFO - ✅ Хранилище закрыто
2025-08-10 00:34:19,663 - aiogram.dispatcher.dispatcher - INFO - Stop polling...
2025-08-10 00:34:19,664 - aiogram - WARNING - Goodbye!
